#!/bin/bash

npm run build
# npm publish

PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
aws s3 cp dist/trucode-${PACKAGE_VERSION}.js s3://${BUCKET_NAME}/${BUCKET_DIR_NAME}/trucode-${PACKAGE_VERSION}.js
